<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- including valheim specific libs -->
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\libs\0Harmony</HintPath>
    </Reference>
    <Reference Include="assembly_valheim">
      <HintPath>..\libs\assembly_valheim</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>..\libs\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\libs\UnityEngine.CoreModule</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\libs\UnityEngine</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" />
  </ItemGroup>

</Project>
